[package]
name = "Hyperion"
version = "0.1.0"
edition = "2024"

[dependencies]
druid = {version = "0.8.3", features = ["image-all"]}
reqwest = {version = "0.12.23", features = ["blocking"]}
scraper = "0.24.0"