[package]
name = "Hyperion"
version = "0.1.0"
edition = "2024"
authors = ["Nathan Heang"]
description = "A simple tool to scrape HTML elements' text from websites."


[dependencies]
reqwest = {version = "0.12.23", features = ["blocking"]}
scraper = "0.24.0"
xilem = "0.3.0"
winit = "0.30.12"